
export const INPUT_FOLLOW_UPDATE = 'INPUT_FOLLOW_UPDATE';
export const ADD_FOLLOW = 'ADD_FOLLOW';
export const REMOVE_FOLLOW = 'REMOVE_FOLLOW';

export const LOADED_TOP_HEADLINES = 'LOADED_TOP_HEADLINES';
export const RESET_TOP_HEADLINES = 'RESET_TOP_HEADLINES';
export const LOADED_FOLLOW_HEADLINES = 'LOADED_FOLLOW_HEADLINES';
export const RESET_FOLLOW_HEADLINES = 'RESET_FOLLOW_HEADLINES';
